### ISSUE TITLE
minimatch deprecated

### ISSUE THREAD

**Issue by dvera123** [gruntjs/grunt-contrib-jshint#260]
minimatch was updated in jshint, but the change has not been reflected in this repo.

is that ok?

**Comment by yankopetrov** [comment]
Please fix the warnings
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

```
├─┬ grunt-contrib-jshint@1.0.0
│ └─┬ jshint@2.9.2
│   ├─┬ cli@0.6.6
│   │ └─┬ glob@3.2.11
│   │   └── minimatch@0.3.0 
│   └── minimatch@2.0.10 
```

**Comment by XhmikosR** [comment]
This was fixed some time ago.

**Comment by EkoJR** [comment]
This still appears to be an issue. Just recently reinstalled too.

```
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```

```
+-- grunt@1.0.3
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| |   `-- minimatch@3.0.4  deduped
| +-- glob@7.0.6
| | `-- minimatch@3.0.4  deduped
| `-- minimatch@3.0.4
+-- grunt-contrib-jshint@1.1.0
| `-- jshint@2.9.6
|   +-- cli@1.0.1
|   | `-- glob@7.1.3
|   |   `-- minimatch@3.0.4  deduped
|   `-- minimatch@3.0.4  deduped
`-- grunt-phplint@0.1.0
  `-- grunt@0.4.5
    +-- findup-sync@0.1.3
    | `-- glob@3.2.11
    |   `-- minimatch@0.3.0
    +-- glob@3.1.21
    | `-- minimatch@0.2.14  deduped
    `-- minimatch@0.2.14
```

**Comment by XhmikosR** [comment]
Doesn't come from jshint, check the dep tree you pasted.

**Comment by EkoJR** [comment]
Yea, that's correct. It's from phplint though.

**Comment by XhmikosR** [comment]
It's unrelated to grunt-contrib-jshint.
